/// Standard reference data the forms pick from: ISO 4217 currencies, ISO 3166
/// countries and IANA time zones.
///
/// These are published standards, not tenant settings. What a form starts with
/// comes from the tenant's own profile (its declared currency and country), and
/// where there is no tenant yet — onboarding a new business — nothing is
/// preselected: a country or currency the person did not choose is exactly the
/// hard-coded default this file replaced (SJ-D53).
library;

/// Active ISO 4217 currency codes and their English names.
const Map<String, String> isoCurrencies = {
  'AED': 'UAE Dirham',
  'AFN': 'Afghan Afghani',
  'ALL': 'Albanian Lek',
  'AMD': 'Armenian Dram',
  'ANG': 'Netherlands Antillean Guilder',
  'AOA': 'Angolan Kwanza',
  'ARS': 'Argentine Peso',
  'AUD': 'Australian Dollar',
  'AWG': 'Aruban Florin',
  'AZN': 'Azerbaijani Manat',
  'BAM': 'Bosnia-Herzegovina Convertible Mark',
  'BBD': 'Barbadian Dollar',
  'BDT': 'Bangladeshi Taka',
  'BGN': 'Bulgarian Lev',
  'BHD': 'Bahraini Dinar',
  'BIF': 'Burundian Franc',
  'BMD': 'Bermudian Dollar',
  'BND': 'Brunei Dollar',
  'BOB': 'Bolivian Boliviano',
  'BRL': 'Brazilian Real',
  'BSD': 'Bahamian Dollar',
  'BTN': 'Bhutanese Ngultrum',
  'BWP': 'Botswana Pula',
  'BYN': 'Belarusian Ruble',
  'BZD': 'Belize Dollar',
  'CAD': 'Canadian Dollar',
  'CDF': 'Congolese Franc',
  'CHF': 'Swiss Franc',
  'CLP': 'Chilean Peso',
  'CNY': 'Chinese Yuan',
  'COP': 'Colombian Peso',
  'CRC': 'Costa Rican Colón',
  'CUP': 'Cuban Peso',
  'CVE': 'Cape Verdean Escudo',
  'CZK': 'Czech Koruna',
  'DJF': 'Djiboutian Franc',
  'DKK': 'Danish Krone',
  'DOP': 'Dominican Peso',
  'DZD': 'Algerian Dinar',
  'EGP': 'Egyptian Pound',
  'ERN': 'Eritrean Nakfa',
  'ETB': 'Ethiopian Birr',
  'EUR': 'Euro',
  'FJD': 'Fijian Dollar',
  'FKP': 'Falkland Islands Pound',
  'GBP': 'British Pound',
  'GEL': 'Georgian Lari',
  'GHS': 'Ghanaian Cedi',
  'GIP': 'Gibraltar Pound',
  'GMD': 'Gambian Dalasi',
  'GNF': 'Guinean Franc',
  'GTQ': 'Guatemalan Quetzal',
  'GYD': 'Guyanese Dollar',
  'HKD': 'Hong Kong Dollar',
  'HNL': 'Honduran Lempira',
  'HTG': 'Haitian Gourde',
  'HUF': 'Hungarian Forint',
  'IDR': 'Indonesian Rupiah',
  'ILS': 'Israeli New Shekel',
  'INR': 'Indian Rupee',
  'IQD': 'Iraqi Dinar',
  'IRR': 'Iranian Rial',
  'ISK': 'Icelandic Króna',
  'JMD': 'Jamaican Dollar',
  'JOD': 'Jordanian Dinar',
  'JPY': 'Japanese Yen',
  'KES': 'Kenyan Shilling',
  'KGS': 'Kyrgystani Som',
  'KHR': 'Cambodian Riel',
  'KMF': 'Comorian Franc',
  'KRW': 'South Korean Won',
  'KWD': 'Kuwaiti Dinar',
  'KYD': 'Cayman Islands Dollar',
  'KZT': 'Kazakhstani Tenge',
  'LAK': 'Laotian Kip',
  'LBP': 'Lebanese Pound',
  'LKR': 'Sri Lankan Rupee',
  'LRD': 'Liberian Dollar',
  'LSL': 'Lesotho Loti',
  'LYD': 'Libyan Dinar',
  'MAD': 'Moroccan Dirham',
  'MDL': 'Moldovan Leu',
  'MGA': 'Malagasy Ariary',
  'MKD': 'Macedonian Denar',
  'MMK': 'Myanmar Kyat',
  'MNT': 'Mongolian Tugrik',
  'MOP': 'Macanese Pataca',
  'MRU': 'Mauritanian Ouguiya',
  'MUR': 'Mauritian Rupee',
  'MVR': 'Maldivian Rufiyaa',
  'MWK': 'Malawian Kwacha',
  'MXN': 'Mexican Peso',
  'MYR': 'Malaysian Ringgit',
  'MZN': 'Mozambican Metical',
  'NAD': 'Namibian Dollar',
  'NGN': 'Nigerian Naira',
  'NIO': 'Nicaraguan Córdoba',
  'NOK': 'Norwegian Krone',
  'NPR': 'Nepalese Rupee',
  'NZD': 'New Zealand Dollar',
  'OMR': 'Omani Rial',
  'PAB': 'Panamanian Balboa',
  'PEN': 'Peruvian Sol',
  'PGK': 'Papua New Guinean Kina',
  'PHP': 'Philippine Peso',
  'PKR': 'Pakistani Rupee',
  'PLN': 'Polish Złoty',
  'PYG': 'Paraguayan Guarani',
  'QAR': 'Qatari Riyal',
  'RON': 'Romanian Leu',
  'RSD': 'Serbian Dinar',
  'RUB': 'Russian Ruble',
  'RWF': 'Rwandan Franc',
  'SAR': 'Saudi Riyal',
  'SBD': 'Solomon Islands Dollar',
  'SCR': 'Seychellois Rupee',
  'SDG': 'Sudanese Pound',
  'SEK': 'Swedish Krona',
  'SGD': 'Singapore Dollar',
  'SLE': 'Sierra Leonean Leone',
  'SOS': 'Somali Shilling',
  'SRD': 'Surinamese Dollar',
  'SSP': 'South Sudanese Pound',
  'STN': 'São Tomé and Príncipe Dobra',
  'SYP': 'Syrian Pound',
  'SZL': 'Swazi Lilangeni',
  'THB': 'Thai Baht',
  'TJS': 'Tajikistani Somoni',
  'TMT': 'Turkmenistani Manat',
  'TND': 'Tunisian Dinar',
  'TOP': 'Tongan Paʻanga',
  'TRY': 'Turkish Lira',
  'TTD': 'Trinidad and Tobago Dollar',
  'TWD': 'New Taiwan Dollar',
  'TZS': 'Tanzanian Shilling',
  'UAH': 'Ukrainian Hryvnia',
  'UGX': 'Ugandan Shilling',
  'USD': 'US Dollar',
  'UYU': 'Uruguayan Peso',
  'UZS': 'Uzbekistani Som',
  'VES': 'Venezuelan Bolívar',
  'VND': 'Vietnamese Dong',
  'VUV': 'Vanuatu Vatu',
  'WST': 'Samoan Tala',
  'XAF': 'Central African CFA Franc',
  'XCD': 'East Caribbean Dollar',
  'XOF': 'West African CFA Franc',
  'XPF': 'CFP Franc',
  'YER': 'Yemeni Rial',
  'ZAR': 'South African Rand',
  'ZMW': 'Zambian Kwacha',
  'ZWL': 'Zimbabwean Dollar',
};

/// ISO 3166-1 alpha-2 country codes, their English names and the currency each
/// trades in — used to suggest a currency once a country is chosen, never to
/// choose a country.
const Map<String, (String, String)> isoCountries = {
  'AE': ('United Arab Emirates', 'AED'),
  'AR': ('Argentina', 'ARS'),
  'AT': ('Austria', 'EUR'),
  'AU': ('Australia', 'AUD'),
  'BD': ('Bangladesh', 'BDT'),
  'BE': ('Belgium', 'EUR'),
  'BG': ('Bulgaria', 'BGN'),
  'BH': ('Bahrain', 'BHD'),
  'BR': ('Brazil', 'BRL'),
  'CA': ('Canada', 'CAD'),
  'CH': ('Switzerland', 'CHF'),
  'CL': ('Chile', 'CLP'),
  'CN': ('China', 'CNY'),
  'CO': ('Colombia', 'COP'),
  'CY': ('Cyprus', 'EUR'),
  'CZ': ('Czechia', 'CZK'),
  'DE': ('Germany', 'EUR'),
  'DK': ('Denmark', 'DKK'),
  'EE': ('Estonia', 'EUR'),
  'EG': ('Egypt', 'EGP'),
  'ES': ('Spain', 'EUR'),
  'FI': ('Finland', 'EUR'),
  'FR': ('France', 'EUR'),
  'GB': ('United Kingdom', 'GBP'),
  'GH': ('Ghana', 'GHS'),
  'GR': ('Greece', 'EUR'),
  'HK': ('Hong Kong', 'HKD'),
  'HR': ('Croatia', 'EUR'),
  'HU': ('Hungary', 'HUF'),
  'ID': ('Indonesia', 'IDR'),
  'IE': ('Ireland', 'EUR'),
  'IL': ('Israel', 'ILS'),
  'IN': ('India', 'INR'),
  'IS': ('Iceland', 'ISK'),
  'IT': ('Italy', 'EUR'),
  'JO': ('Jordan', 'JOD'),
  'JP': ('Japan', 'JPY'),
  'KE': ('Kenya', 'KES'),
  'KR': ('South Korea', 'KRW'),
  'KW': ('Kuwait', 'KWD'),
  'LK': ('Sri Lanka', 'LKR'),
  'LT': ('Lithuania', 'EUR'),
  'LU': ('Luxembourg', 'EUR'),
  'LV': ('Latvia', 'EUR'),
  'MA': ('Morocco', 'MAD'),
  'MT': ('Malta', 'EUR'),
  'MX': ('Mexico', 'MXN'),
  'MY': ('Malaysia', 'MYR'),
  'NG': ('Nigeria', 'NGN'),
  'NL': ('Netherlands', 'EUR'),
  'NO': ('Norway', 'NOK'),
  'NP': ('Nepal', 'NPR'),
  'NZ': ('New Zealand', 'NZD'),
  'OM': ('Oman', 'OMR'),
  'PE': ('Peru', 'PEN'),
  'PH': ('Philippines', 'PHP'),
  'PK': ('Pakistan', 'PKR'),
  'PL': ('Poland', 'PLN'),
  'PT': ('Portugal', 'EUR'),
  'QA': ('Qatar', 'QAR'),
  'RO': ('Romania', 'RON'),
  'RS': ('Serbia', 'RSD'),
  'SA': ('Saudi Arabia', 'SAR'),
  'SE': ('Sweden', 'SEK'),
  'SG': ('Singapore', 'SGD'),
  'SI': ('Slovenia', 'EUR'),
  'SK': ('Slovakia', 'EUR'),
  'TH': ('Thailand', 'THB'),
  'TR': ('Türkiye', 'TRY'),
  'TW': ('Taiwan', 'TWD'),
  'TZ': ('Tanzania', 'TZS'),
  'UA': ('Ukraine', 'UAH'),
  'UG': ('Uganda', 'UGX'),
  'US': ('United States', 'USD'),
  'VN': ('Vietnam', 'VND'),
  'ZA': ('South Africa', 'ZAR'),
};

/// IANA time zones a store is commonly in. The stored value is the zone id
/// itself, so any valid id round-trips even when it is not listed here.
const List<String> ianaTimezones = [
  'UTC',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Africa/Lagos',
  'Africa/Nairobi',
  'America/Bogota',
  'America/Chicago',
  'America/Denver',
  'America/Lima',
  'America/Los_Angeles',
  'America/Mexico_City',
  'America/New_York',
  'America/Santiago',
  'America/Sao_Paulo',
  'America/Toronto',
  'America/Vancouver',
  'Asia/Bangkok',
  'Asia/Colombo',
  'Asia/Dhaka',
  'Asia/Dubai',
  'Asia/Hong_Kong',
  'Asia/Jakarta',
  'Asia/Karachi',
  'Asia/Kathmandu',
  'Asia/Kolkata',
  'Asia/Kuala_Lumpur',
  'Asia/Kuwait',
  'Asia/Manila',
  'Asia/Qatar',
  'Asia/Riyadh',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Tokyo',
  'Atlantic/Reykjavik',
  'Australia/Melbourne',
  'Australia/Perth',
  'Australia/Sydney',
  'Europe/Amsterdam',
  'Europe/Athens',
  'Europe/Berlin',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Dublin',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Europe/Lisbon',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Prague',
  'Europe/Rome',
  'Europe/Stockholm',
  'Europe/Vienna',
  'Europe/Warsaw',
  'Europe/Zurich',
  'Pacific/Auckland',
];

/// The name of the country [code] names (`FR` → *France*); a code this list
/// does not know yet stays as it came.
String countryName(String code) =>
    isoCountries[code.trim().toUpperCase()]?.$1 ?? code;

/// The country a code names, as it reads after "in": *the United Kingdom*,
/// *France*. A code this list does not know yet stays as it came.
String countryInSentence(String code) {
  final name = isoCountries[code.trim().toUpperCase()]?.$1;
  if (name == null) return code;
  const withThe = {
    'United Kingdom',
    'United States',
    'United Arab Emirates',
    'Netherlands',
    'Philippines',
  };
  return withThe.contains(name) ? 'the $name' : name;
}
