/// Standard reference data the forms pick from: ISO 4217 currencies, ISO 3166
/// countries and IANA time zones.
///
/// These are published standards, not tenant settings. What a form starts with
/// comes from the tenant's own profile (its declared currency and country), and
/// where there is no tenant yet — onboarding a new business — nothing is
/// preselected: a country or currency the person did not choose is exactly the
/// hard-coded default this file replaced (SJ-D53).
library;

/// Active ISO 4217 currency codes and their English names.
const Map<String, String> isoCurrencies = {
  'AED': 'UAE Dirham',
  'AFN': 'Afghan Afghani',
  'ALL': 'Albanian Lek',
  'AMD': 'Armenian Dram',
  'ANG': 'Netherlands Antillean Guilder',
  'AOA': 'Angolan Kwanza',
  'ARS': 'Argentine Peso',
  'AUD': 'Australian Dollar',
  'AWG': 'Aruban Florin',
  'AZN': 'Azerbaijani Manat',
  'BAM': 'Bosnia-Herzegovina Convertible Mark',
  'BBD': 'Barbadian Dollar',
  'BDT': 'Bangladeshi Taka',
  'BGN': 'Bulgarian Lev',
  'BHD': 'Bahraini Dinar',
  'BIF': 'Burundian Franc',
  'BMD': 'Bermudian Dollar',
  'BND': 'Brunei Dollar',
  'BOB': 'Bolivian Boliviano',
  'BRL': 'Brazilian Real',
  'BSD': 'Bahamian Dollar',
  'BTN': 'Bhutanese Ngultrum',
  'BWP': 'Botswana Pula',
  'BYN': 'Belarusian Ruble',
  'BZD': 'Belize Dollar',
  'CAD': 'Canadian Dollar',
  'CDF': 'Congolese Franc',
  'CHF': 'Swiss Franc',
  'CLP': 'Chilean Peso',
  'CNY': 'Chinese Yuan',
  'COP': 'Colombian Peso',
  'CRC': 'Costa Rican Colón',
  'CUP': 'Cuban Peso',
  'CVE': 'Cape Verdean Escudo',
  'CZK': 'Czech Koruna',
  'DJF': 'Djiboutian Franc',
  'DKK': 'Danish Krone',
  'DOP': 'Dominican Peso',
  'DZD': 'Algerian Dinar',
  'EGP': 'Egyptian Pound',
  'ERN': 'Eritrean Nakfa',
  'ETB': 'Ethiopian Birr',
  'EUR': 'Euro',
  'FJD': 'Fijian Dollar',
  'FKP': 'Falkland Islands Pound',
  'GBP': 'British Pound',
  'GEL': 'Georgian Lari',
  'GHS': 'Ghanaian Cedi',
  'GIP': 'Gibraltar Pound',
  'GMD': 'Gambian Dalasi',
  'GNF': 'Guinean Franc',
  'GTQ': 'Guatemalan Quetzal',
  'GYD': 'Guyanese Dollar',
  'HKD': 'Hong Kong Dollar',
  'HNL': 'Honduran Lempira',
  'HTG': 'Haitian Gourde',
  'HUF': 'Hungarian Forint',
  'IDR': 'Indonesian Rupiah',
  'ILS': 'Israeli New Shekel',
  'INR': 'Indian Rupee',
  'IQD': 'Iraqi Dinar',
  'IRR': 'Iranian Rial',
  'ISK': 'Icelandic Króna',
  'JMD': 'Jamaican Dollar',
  'JOD': 'Jordanian Dinar',
  'JPY': 'Japanese Yen',
  'KES': 'Kenyan Shilling',
  'KGS': 'Kyrgystani Som',
  'KHR': 'Cambodian Riel',
  'KMF': 'Comorian Franc',
  'KPW': 'North Korean Won',
  'KRW': 'South Korean Won',
  'KWD': 'Kuwaiti Dinar',
  'KYD': 'Cayman Islands Dollar',
  'KZT': 'Kazakhstani Tenge',
  'LAK': 'Laotian Kip',
  'LBP': 'Lebanese Pound',
  'LKR': 'Sri Lankan Rupee',
  'LRD': 'Liberian Dollar',
  'LSL': 'Lesotho Loti',
  'LYD': 'Libyan Dinar',
  'MAD': 'Moroccan Dirham',
  'MDL': 'Moldovan Leu',
  'MGA': 'Malagasy Ariary',
  'MKD': 'Macedonian Denar',
  'MMK': 'Myanmar Kyat',
  'MNT': 'Mongolian Tugrik',
  'MOP': 'Macanese Pataca',
  'MRU': 'Mauritanian Ouguiya',
  'MUR': 'Mauritian Rupee',
  'MVR': 'Maldivian Rufiyaa',
  'MWK': 'Malawian Kwacha',
  'MXN': 'Mexican Peso',
  'MYR': 'Malaysian Ringgit',
  'MZN': 'Mozambican Metical',
  'NAD': 'Namibian Dollar',
  'NGN': 'Nigerian Naira',
  'NIO': 'Nicaraguan Córdoba',
  'NOK': 'Norwegian Krone',
  'NPR': 'Nepalese Rupee',
  'NZD': 'New Zealand Dollar',
  'OMR': 'Omani Rial',
  'PAB': 'Panamanian Balboa',
  'PEN': 'Peruvian Sol',
  'PGK': 'Papua New Guinean Kina',
  'PHP': 'Philippine Peso',
  'PKR': 'Pakistani Rupee',
  'PLN': 'Polish Złoty',
  'PYG': 'Paraguayan Guarani',
  'QAR': 'Qatari Riyal',
  'RON': 'Romanian Leu',
  'RSD': 'Serbian Dinar',
  'RUB': 'Russian Ruble',
  'RWF': 'Rwandan Franc',
  'SAR': 'Saudi Riyal',
  'SBD': 'Solomon Islands Dollar',
  'SCR': 'Seychellois Rupee',
  'SDG': 'Sudanese Pound',
  'SEK': 'Swedish Krona',
  'SGD': 'Singapore Dollar',
  'SHP': 'Saint Helena Pound',
  'SLE': 'Sierra Leonean Leone',
  'SOS': 'Somali Shilling',
  'SRD': 'Surinamese Dollar',
  'SSP': 'South Sudanese Pound',
  'STN': 'São Tomé and Príncipe Dobra',
  'SYP': 'Syrian Pound',
  'SZL': 'Swazi Lilangeni',
  'THB': 'Thai Baht',
  'TJS': 'Tajikistani Somoni',
  'TMT': 'Turkmenistani Manat',
  'TND': 'Tunisian Dinar',
  'TOP': 'Tongan Paʻanga',
  'TRY': 'Turkish Lira',
  'TTD': 'Trinidad and Tobago Dollar',
  'TWD': 'New Taiwan Dollar',
  'TZS': 'Tanzanian Shilling',
  'UAH': 'Ukrainian Hryvnia',
  'UGX': 'Ugandan Shilling',
  'USD': 'US Dollar',
  'UYU': 'Uruguayan Peso',
  'UZS': 'Uzbekistani Som',
  'VES': 'Venezuelan Bolívar',
  'VND': 'Vietnamese Dong',
  'VUV': 'Vanuatu Vatu',
  'WST': 'Samoan Tala',
  'XAF': 'Central African CFA Franc',
  'XCD': 'East Caribbean Dollar',
  'XCG': 'Caribbean Guilder',
  'XOF': 'West African CFA Franc',
  'XPF': 'CFP Franc',
  'YER': 'Yemeni Rial',
  'ZAR': 'South African Rand',
  'ZMW': 'Zambian Kwacha',
  'ZWG': 'Zimbabwe Gold',
  'ZWL': 'Zimbabwean Dollar',
};

/// The ISO 4217 currencies whose minor unit is not two decimal places, and how
/// many they have — every one the JDK's `Currency.getDefaultFractionDigits`
/// answers other than 2 for (withdrawn codes included, since the services
/// still take them). A currency not listed has two, and so has a metal or fund
/// with no minor unit at all (XAU, XDR …), as common-service's `Fx.minorUnits`
/// reads it.
///
/// ISO's table and not intl's CLDR one, on purpose: every service rounds and
/// stores money at ISO's minor units (OrderService, `Fx`, UnitPricing), and
/// CLDR's display digits disagree for fifteen currencies — 0 for the Serbian
/// dinar, the forint, the rupiah and the Pakistani rupee where ISO says 2, and 0
/// for the Iraqi dinar where ISO says 3. A till that read CLDR could not take
/// RSD 129.99 for a sale priced at 129.99.
const Map<String, int> isoMinorUnits = {
  'ADP': 0,
  'BEF': 0,
  'BHD': 3,
  'BIF': 0,
  'BYB': 0,
  'BYR': 0,
  'CLF': 4,
  'CLP': 0,
  'DJF': 0,
  'ESP': 0,
  'GNF': 0,
  'GRD': 0,
  'IQD': 3,
  'ISK': 0,
  'ITL': 0,
  'JOD': 3,
  'JPY': 0,
  'KMF': 0,
  'KRW': 0,
  'KWD': 3,
  'LUF': 0,
  'LYD': 3,
  'MGF': 0,
  'OMR': 3,
  'PTE': 0,
  'PYG': 0,
  'ROL': 0,
  'RWF': 0,
  'TND': 3,
  'TPE': 0,
  'TRL': 0,
  'UGX': 0,
  'UYI': 0,
  'VND': 0,
  'VUV': 0,
  'XAF': 0,
  'XOF': 0,
  'XPF': 0,
};

/// Every assigned ISO 3166-1 alpha-2 country code (all 249), its English short
/// name and the currency each trades in — used to suggest a currency once a
/// country is chosen, never to choose a country. A territory with no currency
/// of its own (Antarctica) suggests none.
///
/// The whole standard and not a selection: the services take every code there
/// is (tenant-svc and every `TenantProfiles` caller check against the JDK's
/// full list), so a list that carried only some of them dropped a real store's
/// country on edit and left a business in Georgia or Mongolia no way to choose
/// its own (location-neutral).
const Map<String, (String, String?)> isoCountries = {
  'AD': ('Andorra', 'EUR'),
  'AE': ('United Arab Emirates', 'AED'),
  'AF': ('Afghanistan', 'AFN'),
  'AG': ('Antigua and Barbuda', 'XCD'),
  'AI': ('Anguilla', 'XCD'),
  'AL': ('Albania', 'ALL'),
  'AM': ('Armenia', 'AMD'),
  'AO': ('Angola', 'AOA'),
  'AQ': ('Antarctica', null),
  'AR': ('Argentina', 'ARS'),
  'AS': ('American Samoa', 'USD'),
  'AT': ('Austria', 'EUR'),
  'AU': ('Australia', 'AUD'),
  'AW': ('Aruba', 'AWG'),
  'AX': ('Åland Islands', 'EUR'),
  'AZ': ('Azerbaijan', 'AZN'),
  'BA': ('Bosnia and Herzegovina', 'BAM'),
  'BB': ('Barbados', 'BBD'),
  'BD': ('Bangladesh', 'BDT'),
  'BE': ('Belgium', 'EUR'),
  'BF': ('Burkina Faso', 'XOF'),
  'BG': ('Bulgaria', 'EUR'),
  'BH': ('Bahrain', 'BHD'),
  'BI': ('Burundi', 'BIF'),
  'BJ': ('Benin', 'XOF'),
  'BL': ('Saint Barthélemy', 'EUR'),
  'BM': ('Bermuda', 'BMD'),
  'BN': ('Brunei', 'BND'),
  'BO': ('Bolivia', 'BOB'),
  'BQ': ('Bonaire, Sint Eustatius and Saba', 'USD'),
  'BR': ('Brazil', 'BRL'),
  'BS': ('Bahamas', 'BSD'),
  'BT': ('Bhutan', 'BTN'),
  'BV': ('Bouvet Island', 'NOK'),
  'BW': ('Botswana', 'BWP'),
  'BY': ('Belarus', 'BYN'),
  'BZ': ('Belize', 'BZD'),
  'CA': ('Canada', 'CAD'),
  'CC': ('Cocos (Keeling) Islands', 'AUD'),
  'CD': ('Congo (Democratic Republic)', 'CDF'),
  'CF': ('Central African Republic', 'XAF'),
  'CG': ('Congo', 'XAF'),
  'CH': ('Switzerland', 'CHF'),
  'CI': ("Côte d'Ivoire", 'XOF'),
  'CK': ('Cook Islands', 'NZD'),
  'CL': ('Chile', 'CLP'),
  'CM': ('Cameroon', 'XAF'),
  'CN': ('China', 'CNY'),
  'CO': ('Colombia', 'COP'),
  'CR': ('Costa Rica', 'CRC'),
  'CU': ('Cuba', 'CUP'),
  'CV': ('Cabo Verde', 'CVE'),
  'CW': ('Curaçao', 'XCG'),
  'CX': ('Christmas Island', 'AUD'),
  'CY': ('Cyprus', 'EUR'),
  'CZ': ('Czechia', 'CZK'),
  'DE': ('Germany', 'EUR'),
  'DJ': ('Djibouti', 'DJF'),
  'DK': ('Denmark', 'DKK'),
  'DM': ('Dominica', 'XCD'),
  'DO': ('Dominican Republic', 'DOP'),
  'DZ': ('Algeria', 'DZD'),
  'EC': ('Ecuador', 'USD'),
  'EE': ('Estonia', 'EUR'),
  'EG': ('Egypt', 'EGP'),
  'EH': ('Western Sahara', 'MAD'),
  'ER': ('Eritrea', 'ERN'),
  'ES': ('Spain', 'EUR'),
  'ET': ('Ethiopia', 'ETB'),
  'FI': ('Finland', 'EUR'),
  'FJ': ('Fiji', 'FJD'),
  'FK': ('Falkland Islands', 'FKP'),
  'FM': ('Micronesia', 'USD'),
  'FO': ('Faroe Islands', 'DKK'),
  'FR': ('France', 'EUR'),
  'GA': ('Gabon', 'XAF'),
  'GB': ('United Kingdom', 'GBP'),
  'GD': ('Grenada', 'XCD'),
  'GE': ('Georgia', 'GEL'),
  'GF': ('French Guiana', 'EUR'),
  'GG': ('Guernsey', 'GBP'),
  'GH': ('Ghana', 'GHS'),
  'GI': ('Gibraltar', 'GIP'),
  'GL': ('Greenland', 'DKK'),
  'GM': ('Gambia', 'GMD'),
  'GN': ('Guinea', 'GNF'),
  'GP': ('Guadeloupe', 'EUR'),
  'GQ': ('Equatorial Guinea', 'XAF'),
  'GR': ('Greece', 'EUR'),
  'GS': ('South Georgia and the South Sandwich Islands', 'GBP'),
  'GT': ('Guatemala', 'GTQ'),
  'GU': ('Guam', 'USD'),
  'GW': ('Guinea-Bissau', 'XOF'),
  'GY': ('Guyana', 'GYD'),
  'HK': ('Hong Kong', 'HKD'),
  'HM': ('Heard Island and McDonald Islands', 'AUD'),
  'HN': ('Honduras', 'HNL'),
  'HR': ('Croatia', 'EUR'),
  'HT': ('Haiti', 'HTG'),
  'HU': ('Hungary', 'HUF'),
  'ID': ('Indonesia', 'IDR'),
  'IE': ('Ireland', 'EUR'),
  'IL': ('Israel', 'ILS'),
  'IM': ('Isle of Man', 'GBP'),
  'IN': ('India', 'INR'),
  'IO': ('British Indian Ocean Territory', 'USD'),
  'IQ': ('Iraq', 'IQD'),
  'IR': ('Iran', 'IRR'),
  'IS': ('Iceland', 'ISK'),
  'IT': ('Italy', 'EUR'),
  'JE': ('Jersey', 'GBP'),
  'JM': ('Jamaica', 'JMD'),
  'JO': ('Jordan', 'JOD'),
  'JP': ('Japan', 'JPY'),
  'KE': ('Kenya', 'KES'),
  'KG': ('Kyrgyzstan', 'KGS'),
  'KH': ('Cambodia', 'KHR'),
  'KI': ('Kiribati', 'AUD'),
  'KM': ('Comoros', 'KMF'),
  'KN': ('Saint Kitts and Nevis', 'XCD'),
  'KP': ('North Korea', 'KPW'),
  'KR': ('South Korea', 'KRW'),
  'KW': ('Kuwait', 'KWD'),
  'KY': ('Cayman Islands', 'KYD'),
  'KZ': ('Kazakhstan', 'KZT'),
  'LA': ('Laos', 'LAK'),
  'LB': ('Lebanon', 'LBP'),
  'LC': ('Saint Lucia', 'XCD'),
  'LI': ('Liechtenstein', 'CHF'),
  'LK': ('Sri Lanka', 'LKR'),
  'LR': ('Liberia', 'LRD'),
  'LS': ('Lesotho', 'LSL'),
  'LT': ('Lithuania', 'EUR'),
  'LU': ('Luxembourg', 'EUR'),
  'LV': ('Latvia', 'EUR'),
  'LY': ('Libya', 'LYD'),
  'MA': ('Morocco', 'MAD'),
  'MC': ('Monaco', 'EUR'),
  'MD': ('Moldova', 'MDL'),
  'ME': ('Montenegro', 'EUR'),
  'MF': ('Saint Martin (French part)', 'EUR'),
  'MG': ('Madagascar', 'MGA'),
  'MH': ('Marshall Islands', 'USD'),
  'MK': ('North Macedonia', 'MKD'),
  'ML': ('Mali', 'XOF'),
  'MM': ('Myanmar', 'MMK'),
  'MN': ('Mongolia', 'MNT'),
  'MO': ('Macao', 'MOP'),
  'MP': ('Northern Mariana Islands', 'USD'),
  'MQ': ('Martinique', 'EUR'),
  'MR': ('Mauritania', 'MRU'),
  'MS': ('Montserrat', 'XCD'),
  'MT': ('Malta', 'EUR'),
  'MU': ('Mauritius', 'MUR'),
  'MV': ('Maldives', 'MVR'),
  'MW': ('Malawi', 'MWK'),
  'MX': ('Mexico', 'MXN'),
  'MY': ('Malaysia', 'MYR'),
  'MZ': ('Mozambique', 'MZN'),
  'NA': ('Namibia', 'NAD'),
  'NC': ('New Caledonia', 'XPF'),
  'NE': ('Niger', 'XOF'),
  'NF': ('Norfolk Island', 'AUD'),
  'NG': ('Nigeria', 'NGN'),
  'NI': ('Nicaragua', 'NIO'),
  'NL': ('Netherlands', 'EUR'),
  'NO': ('Norway', 'NOK'),
  'NP': ('Nepal', 'NPR'),
  'NR': ('Nauru', 'AUD'),
  'NU': ('Niue', 'NZD'),
  'NZ': ('New Zealand', 'NZD'),
  'OM': ('Oman', 'OMR'),
  'PA': ('Panama', 'PAB'),
  'PE': ('Peru', 'PEN'),
  'PF': ('French Polynesia', 'XPF'),
  'PG': ('Papua New Guinea', 'PGK'),
  'PH': ('Philippines', 'PHP'),
  'PK': ('Pakistan', 'PKR'),
  'PL': ('Poland', 'PLN'),
  'PM': ('Saint Pierre and Miquelon', 'EUR'),
  'PN': ('Pitcairn Islands', 'NZD'),
  'PR': ('Puerto Rico', 'USD'),
  'PS': ('Palestine', 'ILS'),
  'PT': ('Portugal', 'EUR'),
  'PW': ('Palau', 'USD'),
  'PY': ('Paraguay', 'PYG'),
  'QA': ('Qatar', 'QAR'),
  'RE': ('Réunion', 'EUR'),
  'RO': ('Romania', 'RON'),
  'RS': ('Serbia', 'RSD'),
  'RU': ('Russia', 'RUB'),
  'RW': ('Rwanda', 'RWF'),
  'SA': ('Saudi Arabia', 'SAR'),
  'SB': ('Solomon Islands', 'SBD'),
  'SC': ('Seychelles', 'SCR'),
  'SD': ('Sudan', 'SDG'),
  'SE': ('Sweden', 'SEK'),
  'SG': ('Singapore', 'SGD'),
  'SH': ('Saint Helena, Ascension and Tristan da Cunha', 'SHP'),
  'SI': ('Slovenia', 'EUR'),
  'SJ': ('Svalbard and Jan Mayen', 'NOK'),
  'SK': ('Slovakia', 'EUR'),
  'SL': ('Sierra Leone', 'SLE'),
  'SM': ('San Marino', 'EUR'),
  'SN': ('Senegal', 'XOF'),
  'SO': ('Somalia', 'SOS'),
  'SR': ('Suriname', 'SRD'),
  'SS': ('South Sudan', 'SSP'),
  'ST': ('São Tomé and Príncipe', 'STN'),
  'SV': ('El Salvador', 'USD'),
  'SX': ('Sint Maarten (Dutch part)', 'XCG'),
  'SY': ('Syria', 'SYP'),
  'SZ': ('Eswatini', 'SZL'),
  'TC': ('Turks and Caicos Islands', 'USD'),
  'TD': ('Chad', 'XAF'),
  'TF': ('French Southern Territories', 'EUR'),
  'TG': ('Togo', 'XOF'),
  'TH': ('Thailand', 'THB'),
  'TJ': ('Tajikistan', 'TJS'),
  'TK': ('Tokelau', 'NZD'),
  'TL': ('Timor-Leste', 'USD'),
  'TM': ('Turkmenistan', 'TMT'),
  'TN': ('Tunisia', 'TND'),
  'TO': ('Tonga', 'TOP'),
  'TR': ('Türkiye', 'TRY'),
  'TT': ('Trinidad and Tobago', 'TTD'),
  'TV': ('Tuvalu', 'AUD'),
  'TW': ('Taiwan', 'TWD'),
  'TZ': ('Tanzania', 'TZS'),
  'UA': ('Ukraine', 'UAH'),
  'UG': ('Uganda', 'UGX'),
  'UM': ('United States Minor Outlying Islands', 'USD'),
  'US': ('United States', 'USD'),
  'UY': ('Uruguay', 'UYU'),
  'UZ': ('Uzbekistan', 'UZS'),
  'VA': ('Holy See (Vatican City)', 'EUR'),
  'VC': ('Saint Vincent and the Grenadines', 'XCD'),
  'VE': ('Venezuela', 'VES'),
  'VG': ('Virgin Islands (British)', 'USD'),
  'VI': ('Virgin Islands (U.S.)', 'USD'),
  'VN': ('Vietnam', 'VND'),
  'VU': ('Vanuatu', 'VUV'),
  'WF': ('Wallis and Futuna', 'XPF'),
  'WS': ('Samoa', 'WST'),
  'YE': ('Yemen', 'YER'),
  'YT': ('Mayotte', 'EUR'),
  'ZA': ('South Africa', 'ZAR'),
  'ZM': ('Zambia', 'ZMW'),
  'ZW': ('Zimbabwe', 'ZWG'),
};

/// Whether [code] names a country: exactly one of [isoCountries], however it
/// is cased or spaced.
///
/// Exact, because the list is the services' own set (tenant-svc and every
/// `TenantProfiles` caller check against the JDK's `Locale.getISOCountries`):
/// a code it does not carry — reserved or user-assigned (UK, EU, XK), withdrawn
/// (YU), or merely of the right shape (JX) — is one the services answer
/// `COUNTRY_INVALID` to, so a form shows it as needing a country rather than
/// keep it and fail on save.
bool isCountryCode(String code) =>
    isoCountries.containsKey(code.trim().toUpperCase());

/// IANA time zones a store is commonly in. The stored value is the zone id
/// itself, so any valid id round-trips even when it is not listed here.
const List<String> ianaTimezones = [
  'UTC',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Africa/Lagos',
  'Africa/Nairobi',
  'America/Bogota',
  'America/Chicago',
  'America/Denver',
  'America/Lima',
  'America/Los_Angeles',
  'America/Mexico_City',
  'America/New_York',
  'America/Santiago',
  'America/Sao_Paulo',
  'America/Toronto',
  'America/Vancouver',
  'Asia/Bangkok',
  'Asia/Colombo',
  'Asia/Dhaka',
  'Asia/Dubai',
  'Asia/Hong_Kong',
  'Asia/Jakarta',
  'Asia/Karachi',
  'Asia/Kathmandu',
  'Asia/Kolkata',
  'Asia/Kuala_Lumpur',
  'Asia/Kuwait',
  'Asia/Manila',
  'Asia/Qatar',
  'Asia/Riyadh',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Tokyo',
  'Atlantic/Reykjavik',
  'Australia/Melbourne',
  'Australia/Perth',
  'Australia/Sydney',
  'Europe/Amsterdam',
  'Europe/Athens',
  'Europe/Berlin',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Dublin',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Europe/Lisbon',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Prague',
  'Europe/Rome',
  'Europe/Stockholm',
  'Europe/Vienna',
  'Europe/Warsaw',
  'Europe/Zurich',
  'Pacific/Auckland',
];

/// The name of the country [code] names (`FR` → *France*); a code this list
/// does not know yet stays as it came.
String countryName(String code) =>
    isoCountries[code.trim().toUpperCase()]?.$1 ?? code;

/// The country a code names, as it reads after "in": *the United Kingdom*,
/// *France*. A code this list does not know yet stays as it came.
String countryInSentence(String code) {
  final name = isoCountries[code.trim().toUpperCase()]?.$1;
  if (name == null) return code;
  return _takesThe(name) ? 'the $name' : name;
}

/// The names English writes with "the": a plural or a union of parts (the
/// Netherlands, the Cayman Islands, the United States), a republic or a
/// territory named for what it is, and a few by custom (the Gambia).
bool _takesThe(String name) {
  const byName = {
    'Bahamas',
    'Comoros',
    'Congo',
    'Congo (Democratic Republic)',
    'Gambia',
    'Holy See (Vatican City)',
    'Isle of Man',
    'Maldives',
    'Netherlands',
    'Philippines',
    'Seychelles',
  };
  if (byName.contains(name)) return true;
  if (name.startsWith('United ')) return true;
  if (name.startsWith('Virgin Islands')) return true;
  return name.endsWith(' Islands') ||
      name.endsWith(' Republic') ||
      name.endsWith(' Territory') ||
      name.endsWith(' Territories');
}
